from njunmt.decoders.rnn_decoder import AttentionDecoder
from njunmt.decoders.rnn_decoder import CondAttentionDecoder
from njunmt.decoders.rnn_decoder import SimpleDecoder
from njunmt.decoders.transformer_decoder import TransformerDecoder